pangea/pangea/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', page, name='start-page'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pangea/posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    # Посты
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('delete/<int:pk>/', views.delete_post, name='delete_post'),

    # Архив
    path('archive/', views.archive_list, name='archive_list'),
    path('<int:pk>/archive/', views.archive_post, name='archive_post'),
    path('return_post/<int:pk>/', views.return_post, name='return_post'),

    # Избранное
    path('favorite/', views.favorite_list, name='favorite_list'),
    path('<int:pk>/favorite/', views.favorite_post, name='favorite_post'),
    path('remove_favorite/<int:pk>/', views.remove_favorite_post, name='remove_favorite_post'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pangea/users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pangea/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images/', null=True, blank=True)
    phone_number = models.CharField(max_length=20)

pangea/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'login_form', 'style': 'margin-bottom: 30px', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'login_form', 'style': 'margin-bottom: 15px', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'login_form', 'style': 'margin-bottom: 14px', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'login_form', 'style': 'margin-bottom: 14px', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'login_form', 'style': 'margin-bottom: 14px', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'login_form', 'style': 'margin-bottom: 14px', 'placeholder': 'Введите адрес эл. почты'}))
    phone_number = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
        'type': 'tel', 'class': 'login_form', 'style': 'margin-bottom: 14px', 'placeholder': 'Введите номер телефона'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'login_form', 'style': 'margin-bottom: 14px', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'login_form', 'style': 'margin-bottom: 14px', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'phone_number', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-2'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-2'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'type': 'tel', 'class': 'form-control py-2'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control-custom w-100 p-2 border rounded '
                                                                      'bg-dark-subtle', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control-custom w-100 p-2 border rounded '
                                                                   'bg-dark-subtle', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'image', 'username', 'email')

pangea/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from posts.models import Post

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm

def index(request):
    return render(request, 'users/profile.html')


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            messages.success(request, 'Приветствуем на нашем сайте по поиску руммейтов! Мы поможем вам найти подходящего соседа для совместного проживания. Начните свой поиск прямо сейчас!')
            username = request.POST['username']
            password = request.POST['password']
            remember_me = request.POST.get('remember_me')
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                if remember_me:
                    request.session.set_expiry(1209600)
                return HttpResponseRedirect(reverse('posts:post_list'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Поздравляем! Вы успешно зарегистрированы!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)

    user = request.user
    my_posts = Post.objects.filter(user_id=user, archived=False).order_by('-created_at')
    archived_posts_count = Post.objects.filter(user_id=user, archived=True).count()
    context = {
        'user': user,
        'my_posts': my_posts,
        'archived_posts_count': archived_posts_count,
        'title': 'Профиль', 
        'form': form
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:login'))

pangea/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link href="{% static 'css/posts/main.css' %}" rel="stylesheet"/>
    {% block css %}{% endblock %}
  </head>
  <body style="background-color: #123e3b;">
    {% block content %}
    {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

pangea/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %}Войти на Pangea{% endblock %}
{% block css %}<link href="{% static 'css/users/auth.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<div class="login_wrapper">
    <div class="container_login">
        <a href="javascript:history.back()" class="login_arrow-back">
            <img src="{% static 'img/users/arrow-back.png' %}" alt="">
        </a>
        <div class="login_main-form">
            <img src="{% static 'img/users/logo-white.png' %}" alt="logo" style="width: 35px;" class="mb-1" />
            <div class="login_title mb-3">Вход</div>
            <div class="">
                {% if messages or form.non_field_errors %}
                <div class="alert
                    {% if messages %} alert-success {% else %} alert-danger {% endif %} alert-dismissible fade show"
                    role="alert" 
                    style="width: 500px;"
                >
                    {% if messages %}
                    {% for message in messages %}
                    {{ message }}
                    {% endfor %}
                    {% else %}
                    {{ form.non_field_errors }}
                    {% endif %}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
            </div>
            <div class="text-center">
                <form action="{% url 'users:login' %}" method="post" class="">
                    {% csrf_token %}
                    <div class="">
                        {{ form.username }}
                    </div>
                    <div class="">
                        {{ form.password }}
                    </div>
                    <div class="text-start mx-2 d-flex gap-2" style="margin-bottom: 27px;">
                        <input style="width: 14px; cursor: pointer;" type="checkbox" name="remember_me" id="remember_me">
                        <label class="login_remember_text" for="remember_me">
                            Запомнить меня
                        </label>
                    </div>
                    <button type="submit" class="login_button">Log in</button><br/>
                    <a href="{% url 'users:registration' %}" class="login_reg-btn">Зарегистрироваться</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

pangea/users/templates/users/profile.html
{% extends 'posts/base.html' %}
{% load static %}
{% block title %}Личная страница {{ user }}{% endblock %}
{% block css %}
<link href="{% static 'css/users/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="main_info">
    <div class="main_info_image">
        <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/users/default-pangea.png' %} {% endif %}"
            class="rounded-4" style="width: 100%; height: 100%; object-fit: cover; ">
    </div>
    <div class="main_info_text d-flex flex-column justify-content-between">
        <div class="main_info_user-desc">
            <h1>{{ user }}</h1>
            <div class="d-flex gap-3">
                <div>
                    <div>Имя: </div>
                    <div>Номер телефона: </div>
                    <div>Электронная почта: </div>
                    <div>Дата регистрации: </div>
                </div>
                <div>
                    <div>
                        {% if user.first_name %}
                        {{ user.first_name }} {{ user.last_name }}
                        {% else %}
                        -
                        {% endif %}
                    </div>
                    <div>
                        {% if user.phone_number %}
                        {{ user.phone_number }}
                        {% else %}
                        -
                        {% endif %}
                    </div>
                    <div>{{ user.email }}</div>
                    <div>{{ user.date_joined }}</div>
                </div>
            </div>
        </div>
        <div>
            <button id="btn" class="btn btn-light">Изменить</button>
            <a href="{% url 'posts:archive_list' %}" class="btn" style="background-color: #2c786c; color: #fff;">
                Мой архив <span class="badge badge-light">{{ archived_posts_count }}</span>
            </a>
            <a href="{% url 'users:logout' %}" class="btn btn-danger">Выйти</a>
        </div>
    </div>
</div>

<form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data" id="form" class="edit_form">
    {% csrf_token %}
    <div class="d-flex justify-content-between gap-3">
        <div class="w-100">
            <label class="form-label" for="{{ form.first_name.id_for_label }}">Имя</label>
            {{ form.first_name }}
        </div>
        <div class="w-100">
            <label class="form-label" for="{{ form.last_name.id_for_label }}">Фамилия</label>
            {{ form.last_name }}
        </div>
    </div>
    <div class="d-flex justify-content-between gap-3 my-3">
        <div class="w-100">
            <label class="form-label" for="{{ form.phone_number.id_for_label }}">Номер телефона</label>
            {{ form.phone_number }}
        </div>
        <div class="w-100">
            <label class="form-label" for="{{ form.image.id_for_label }}">
                Выберите изображение
            </label>
            {{ form.image }}
        </div>
    </div>
    <div class="d-flex justify-content-between gap-3" style="margin-bottom: 20px;">
        <div class="w-100">
            <label class="form-label" for="{{ form.username.id_for_label }}">Имя пользователя</label>
            {{ form.username }}
        </div>
        <div class="w-100">
            <label class="form-label" for="{{ form.email.id_for_label }}">
                Адрес электронной почты
            </label>
            {{ form.email }}
        </div>
    </div>
    <div class="text-center">
        <input class="btn btn-success" type="submit" value="Сохранить">
    </div>
</form>

{% if my_posts %}
<h1 class="my_posts_title">Мои объявления</h1>
{% endif %}
<div class="my_posts">
    {% if my_posts %}
    {% for post in my_posts %}
    <div class="my_post">

        {% if post.image %}
        <a href="{% url 'posts:post_detail' post.pk %}" class="image-container">
            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="my_post_img">
        </a>
        {% else %}
        <a href="{% url 'posts:post_detail' post.pk %}" class="image-container">
            <img src="{% static 'img/posts/default_img.png'%}" alt="{{ post.title }}" class="my_post_img">
        </a>
        {% endif %}
        <div class="p-3">
            <h5 class="my_post_title">{{ post.title }}</h5>
            <div class="my_post_desc">{{ post.description }}</div>
            <a href="{% url 'posts:post_detail' post.pk %}" class="my_post_detail_link">Подробнее</a>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>
<script>
    const btn = document.getElementById('btn')
    const form = document.getElementById('form')
    btn.addEventListener('click', () => {
        form.classList.toggle('show')
    })
</script>
{% endblock %}

pangea/users/templates/users/registration.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %}Регистрация на Pangea{% endblock %}
{% block css %}
<link href="{% static 'css/users/auth.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<div class="login_wrapper">
    <div class="container_login">
        <a href="javascript:history.back()" class="login_arrow-back">
            <img src="{% static 'img/users/arrow-back.png' %}" alt="">
        </a>
        <div class="login_main-form">
            <img src="{% static 'img/users/logo-white.png' %}" alt="logo" style="width: 35px;" class="mb-1" />
            <div class="login_title mb-3">Регистрация</div>
            <div>
                {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                    {{ form.errors }}
                    <button type="button" class="btn-close" aria-label="Close" data-dismiss="alert"></button>
                </div>
                {% endif %}
            </div>
            <div class="text-center">
                <form action="{% url 'users:registration' %}" method="post" class="">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.first_name }}
                    </div>
                    <div class="form-group">
                        {{ form.last_name }}
                    </div>
                    <div class="form-group">
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        {{ form.phone_number }}
                    </div>
                    <div class="form-group">
                        {{ form.password1 }}
                    </div>
                    <div class="form-group">
                        {{ form.password2 }}
                    </div>
                    <button type="submit" class="login_button" style="margin-top: 8px;">Авторизоваться</button><br/>
                    <a href="{% url 'users:login' %}" class="login_reg-btn">Войти в аккаунт</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}