pangea/pangea/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', page, name='start-page'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pangea/posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    # Посты
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('delete/<int:pk>/', views.delete_post, name='delete_post'),

    # Архив
    path('archive/', views.archive_list, name='archive_list'),
    path('<int:pk>/archive/', views.archive_post, name='archive_post'),
    path('return_post/<int:pk>/', views.return_post, name='return_post'),

    # Избранное
    path('favorite/', views.favorite_list, name='favorite_list'),
    path('<int:pk>/favorite/', views.favorite_post, name='favorite_post'),
    path('remove_favorite/<int:pk>/', views.remove_favorite_post, name='remove_favorite_post'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pangea/users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pangea/posts/models.py
from django.db import models
from users.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(null=False, max_length=255)
    description = models.CharField(null=False, max_length=2000)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cost = models.IntegerField(blank=True, null=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    archived = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.user.username} - {self.post.title}'

pangea/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    title = forms.CharField(label='Заголовок', widget=forms.TextInput(attrs={'class': 'form-input'}))
    description = forms.CharField(label='Описание', widget=forms.Textarea(attrs={'class': 'form-input form-input_desc'}))
    cost = forms.IntegerField(required=False, min_value=None, label='Цена (в тенге)', widget=forms.NumberInput(attrs={'class': 'form-input'}))
    image = forms.ImageField(label='Фото', widget=forms.FileInput(attrs={'class': 'form-image form-control'}), required=False)
    class Meta:
        model = Post
        fields = ('title', 'description', 'cost', 'image')


class PostDeleteForm(forms.Form):
    is_rent = forms.BooleanField(label='Вы сдали квартиру?', required=False)

pangea/posts/views.py
from datetime import timezone
from django.core.files.storage import default_storage
from django.shortcuts import render, redirect, get_object_or_404, redirect
from .models import Post, Favorite
from rent.models import Rent
from .forms import PostDeleteForm, PostForm
from django.contrib import messages


def post_list(request):
    user = request.user
    posts = Post.objects.filter(archived=False).order_by('-created_at')
    favorites = []
    if user.is_authenticated:
        favorites = Favorite.objects.filter(user_id=user.id, post__in=posts)
    posts_count = Post.objects.filter(archived=False).count()
    archive_count = Post.objects.filter(user_id=user.id, archived=True).count()
    favorite_count = Favorite.objects.filter(user_id=user.id).count()
    favorite_posts = favorites.values_list('post', flat=True) if favorites else []
    return render(request, 'posts/post_list.html', {'posts': posts, 'favorite_posts': favorite_posts, 'posts_count': posts_count, 'archive_count': archive_count, 'favorite_count': favorite_count })


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user_id = request.user
            messages.success(request, 'Ваше объявление было успешно опубликовано!')
            post.save()
            return redirect('/posts/')
    else:
        form = PostForm()
    return render(request, 'posts/post_add.html', {'form': form})

def page(request):
    return render(request, 'posts/start-page.html')


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    is_favorite = False
    if request.user.is_authenticated:
        is_favorite = Favorite.objects.filter(user=request.user, post=post).exists()
    return render(request, 'posts/post_detail.html', {'post': post, 'is_favorite': is_favorite})


def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = PostDeleteForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            is_rent = form.cleaned_data['is_rent']
            rent = Rent.objects.create(user_id=request.user, post_id=post, is_rent=is_rent)
            rent.save()
            post.delete()
            return redirect('posts:post_list')
    
    return render(request, 'posts/post_delete.html', {'post': post})


def archive_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.archived = True
    messages.success(request, 'Ваше объявление было успешно добавлено в архив!')
    post.save()
    return redirect('posts:post_list')

def return_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.archived = False
    messages.success(request, 'Ваше объявление было успешно опубликовано!')
    post.save()
    return redirect('posts:post_list')

def archive_list(request):
    user = request.user
    posts = Post.objects.filter(user_id=user, archived=True).order_by('-created_at')
    posts_count = Post.objects.filter(archived=False).count()
    archive_count = Post.objects.filter(user_id=user, archived=True).count()
    favorite_count = Favorite.objects.filter(user=user).count()
    return render(request, 'posts/archive_list.html', {'posts': posts, 'posts_count': posts_count, 'archive_count': archive_count, 'favorite_count': favorite_count})

def favorite_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    favorite, created = Favorite.objects.get_or_create(user=request.user, post=post)
    messages.success(request, 'Ваше объявление было успешно добавлено в избранное!')
    return redirect('posts:post_list')

def remove_favorite_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    Favorite.objects.filter(user=request.user, post=post).delete()
    messages.success(request, 'Ваше объявление было успешно удалено из избранного!')
    return redirect('posts:post_list')

def favorite_list(request):
    user = request.user
    favorites = Favorite.objects.filter(user=request.user).order_by('-created_at')
    posts_count = Post.objects.filter(archived=False).count()
    archive_count = Post.objects.filter(user_id=user, archived=True).count()
    favorite_count = Favorite.objects.filter(user=user).count()
    return render(request, 'posts/favorite_list.html', {'favorites': favorites, 'posts_count': posts_count, 'archive_count': archive_count, 'favorite_count': favorite_count})

pangea/posts/templates/posts/archive_list.html
{% extends 'posts/base.html' %}
{% load static %}
{% block title %}Архив{% endblock %}
{% block css %}
<link href="{% static 'css/posts/post_list.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<div class="post_list_main-wrapper">
  {% if messages or form.non_field_errors %}
<div class="alert {% if messages %} alert-success {% else %} alert-danger {% endif %} alert-dismissible fade show"
  role="alert">
  {% if messages %}
  {% for message in messages %}
  {{ message }}
  {% endfor %}
  {% else %}
  {{ form.non_field_errors }}
  {% endif %}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
<div class="">
  <div class="d-flex flex-column justify-content-center">
    <div class="mb-5">
      <a href="{% url 'posts:post_list' %}" class="btn" style="background-color: #2c786c; color: #fff;">Все
        объявления<span class="badge badge-light">{{ posts_count }}</span></a>
      {% if user.is_authenticated %}
      <a href="{% url 'posts:archive_list' %}" class="btn" style="background-color: #56c4b4; color: #fff;">Архив<span
          class="badge badge-light">{{ archive_count }}</span></a>
      <a href="{% url 'posts:favorite_list' %}" class="btn"
        style="background-color: #2c786c; color: #fff;">Избранное<span class="badge badge-light">{{ favorite_count}}</span></a>
      {% endif %}
    </div>
    <h1 class="text-light mb-5">Архивированные посты</h1>
    {% if posts %}
    {% for post in posts %}
    <div class="mb-4 post_list_wrapper">
      <div class="d-flex">
        {% if post.image %}
        <a href="{% url 'posts:post_detail' post.pk %}" class="image-container">
          <img src="{{ post.image.url }}" alt="{{ post.title }}" width="253" class="post_img">
        </a>
        {% else %}
        <a href="{% url 'posts:post_detail' post.pk %}" class="image-container">
          <img src="{% static 'img/posts/default_img.png'%}" alt="{{ post.title }}" width="253" class="post_img">
        </a>
        {% endif %}
        <div class="d-flex justify-content-between w-100">
          <div class="post_main-info">
            <div>
              {% if post.user_id.first_name %}
              <div class="post_author-name">{{ post.user_id.first_name }} {{ post.user_id.last_name }}</div>
              {% endif %}
              <!-- для планшетки -->
              <div class="post_cost_wrapper_tablet">
                {% if post.user_id.first_name %}
                  <div class="post_author-name post_author-name_tablet">{{ post.user_id.first_name }} {{ post.user_id.last_name }}</div>
                {% endif %}
                {% if post.cost %}
                <div class="post_cost">{{ post.cost }}тг</div>
                {% endif %}
              </div>
              <!--  -->
              <h5 class="post_title">{{ post.title }} <span>{% if post.is_favorite %}
                  <svg fill="#dc3623" height="24px" width="24px" version="1.1" id="Capa_1"
                    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 230 230"
                    xml:space="preserve" stroke="#dc3623">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                      <path
                        d="M213.588,120.982L115,213.445l-98.588-92.463C-6.537,96.466-5.26,57.99,19.248,35.047l2.227-2.083 c24.51-22.942,62.984-21.674,85.934,2.842L115,43.709l7.592-7.903c22.949-24.516,61.424-25.784,85.936-2.842l2.227,2.083 C235.26,57.99,236.537,96.466,213.588,120.982z">
                      </path>
                    </g>
                  </svg>

                  {% endif %}</span>
                <span class="text-warning fs-6">
                  {% if post.archived %}
                  (в архиве)
                  {% endif %}
                </span>
              </h5>
              <div class="post_desc">{{ post.description }}</div>
            </div>
            <a href="{% url 'posts:post_detail' post.pk %}" class="post_detail_link">Подробнее</a>
          </div>
          <div class="post_cost_wrapper">
            {% if post.cost %}
            <div class="post_cost">{{ post.cost }}тг</div>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="post_author_info post_author_info_tablet">
        <div style="min-width: 230px;">Алматы | <small>{{ post.created_at }}</small></div>
        {% if user.is_authenticated %}
        <a href="{% url 'posts:post_detail' post.pk %}" class="post_detail_link post_detail_link_tablet">Подробнее</a>
        {% else %}
        <a href="{% url 'users:login' %}" class="post_detail_link post_detail_link_tablet">Подробнее</a>
        {% endif %}
      </div>
      <div class="post_author_info">
        <div>Алматы |</div>
        <small>{{ post.created_at }}</small>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h2 class="text-light">Пока объявлений нет</h2>
    {% endif %}
  </div>
</div>
</div>

{% endblock %}

pangea/posts/templates/posts/favorite_list.html
{% extends 'posts/base.html' %}
{% load static %}
{% block title %}Избранное{% endblock %}
{% block css %}
<link href="{% static 'css/posts/post_list.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<div class="post_list_main-wrapper">
    {% if messages or form.non_field_errors %}
<div class="alert {% if messages %} alert-success {% else %} alert-danger {% endif %} alert-dismissible fade show"
    role="alert">
    {% if messages %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    {% else %}
    {{ form.non_field_errors }}
    {% endif %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
<div class="">
    <div class="d-flex flex-column justify-content-center">
        <div class="mb-5">
            <a href="{% url 'posts:post_list' %}" class="btn" style="background-color: #2c786c; color: #fff;">Все
                объявления<span class="badge badge-light">{{ posts_count }}</span></a>
            {% if user.is_authenticated %}
            <a href="{% url 'posts:archive_list' %}" class="btn"
                style="background-color: #2c786c; color: #fff;">Архив<span class="badge badge-light">{{ archive_count}}</span></a>
            <a href="{% url 'posts:favorite_list' %}" class="btn" style="background-color: #56c4b4; color: #fff;">Избранное<span class="badge badge-light">{{ favorite_count }}</span></a>
            {% endif %}
        </div>
        <h1 class="text-light mb-5">Избранные посты</h1>
        {% if favorites %}
        {% for favorite in favorites %}
        <div class="mb-4 post_list_wrapper">
            <div class="d-flex">
                {% if favorite.post.image %}
                <img src="{{ favorite.post.image.url }}" alt="{{ favorite.post.title }}" width="253" class="post_img">
                {% else %}
                <img src="{% static 'img/posts/default_img.png'%}" alt="{{ favorite.post.title }}" width="253" class="post_img">
                {% endif %}
                <div class="d-flex justify-content-between w-100">
                    <div class="post_main-info">
                        <div>
                            {% if favorite.post.user_id.first_name %}
                            <div class="post_author-name">{{ favorite.post.user_id.first_name }} {{ favorite.post.user_id.last_name }}</div>
                            {% endif %}
                            <!-- для планшетки -->
                            <div class="post_cost_wrapper_tablet">
                                {% if favorite.post.user_id.first_name %}
                                <div class="post_author-name post_author-name_tablet">{{ favorite.post.user_id.first_name }} {{ favorite.post.user_id.last_name }}</div>
                                {% endif %}
                                {% if favorite.post.cost %}
                                <div class="post_cost">{{ favorite.post.cost }}тг</div>
                                {% endif %}
                            </div>
                            <!--  -->
                            <h5 class="post_title">{{ favorite.post.title }} <span>
                                    <svg fill="#dc3623" height="24px" width="24px" version="1.1" id="Capa_1"
                                        xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                        viewBox="0 0 230 230" xml:space="preserve" stroke="#dc3623">
                                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round">
                                        </g>
                                        <g id="SVGRepo_iconCarrier">
                                            <path
                                                d="M213.588,120.982L115,213.445l-98.588-92.463C-6.537,96.466-5.26,57.99,19.248,35.047l2.227-2.083 c24.51-22.942,62.984-21.674,85.934,2.842L115,43.709l7.592-7.903c22.949-24.516,61.424-25.784,85.936-2.842l2.227,2.083 C235.26,57.99,236.537,96.466,213.588,120.982z">
                                            </path>
                                        </g>
                                    </svg></span>
                                <span class="text-warning fs-6">
                                    {% if favorite.post.archived %}
                                    (в архиве)
                                    {% endif %}
                                </span>
                            </h5>
                            <div class="post_desc">{{ favorite.post.description }}</div>
                        </div>
                        <a href="{% url 'posts:post_detail' favorite.post.pk %}" class="post_detail_link">Подробнее</a>
                    </div>
                    <div class="post_cost_wrapper">
                        {% if favorite.post.cost %}
                        <div class="post_cost">{{ favorite.post.cost }}тг</div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- для планшетки -->
            <div class="post_author_info post_author_info_tablet">
                <div style="min-width: 230px;">Алматы | <small>{{ favorite.post.created_at }}</small></div>
                {% if user.is_authenticated %}
                <a href="{% url 'posts:post_detail' favorite.post.pk %}" class="post_detail_link post_detail_link_tablet">Подробнее</a>
                {% else %}
                <a href="{% url 'users:login' %}" class="post_detail_link post_detail_link_tablet">Подробнее</a>
                {% endif %}
          </div>
          <!--  -->
            <div class="post_author_info">
                <div>Алматы |</div>
                <small>{{ favorite.post.created_at }}</small>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h2 class="text-light">Пока объявлений нет</h2>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

pangea/posts/templates/posts/post_add.html
{% extends 'posts/base.html' %}
{% load static %}
{% block title %}Подать объявление{% endblock %}
{% block css %}
<link href="{% static 'css/posts/post_add.css' %}" rel="stylesheet" />{% endblock %}
{% block content %}
<div class="post-add_wrapper" style="margin-top: 5%;">
    <div>
        <div class="create_post_with_tg">
            <p>Добро пожаловать на нашу главную страницу! Если вы хотите разместить свое объявление по поиску сожителя или
                вы сами ищите жилье, либо у вас есть вопросы, переходите по ссылке на наш телеграм и свяжитесь с нами
                <a href="https://t.me/s_dkvaa">@s_dkvaa</a></p>

            <p>Мы готовы помочь вам создать идеальное пространство для проживания!</p>
        </div>
    </div>
</div>
{% endblock %}

pangea/posts/templates/posts/post_delete.html
{% extends 'posts/base.html' %}
{% block title %}Удалить объявление{% endblock %}
{% block content %}
<div class="d-flex flex-column justify-content-between align-items-center bg-success-subtle p-3 border border-info rounded w-75" style="height: 400px; color: #2c786c; margin: 0 auto;">
  <h1 class="h-25">Удалить объявление</h1>
  <form method="post" class="h-75 d-flex flex-column justify-content-between">
    {% csrf_token %}
    <h5 class="my-3">Уверены ли вы, что хотите удалить объявление "{{ post.title }}"?</h5>

    <div class="text-center my-4">
      <h6>Удалось ли вам сдать квартиру?</h6>
      <div>
        <input type="radio" name="is_rent" value="True" class="form-check-input">Да
        <input type="radio" name="is_rent" value="False" class="form-check-input" style="margin-left: 15px;">Нет<br>
      </div>
    </div>

    <button type="submit" class="btn btn-danger">Удалить</button>
  </form>
</div>
{% endblock %}

pangea/posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %}
{% load static %}
{% block title %}Объявление: {{ post.title }}{% endblock %}
{% block css %}
<link href="{% static 'css/posts/post_detail.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
<div class="post_detail_main-wrapper">
  <a href="javascript:history.back()" class="login_arrow-back">
    <img src="{% static 'img/users/arrow-back.png' %}" alt="">
  </a>
  {% if messages or form.non_field_errors %}
  <div class="alert {% if messages %} alert-success {% else %} alert-danger {% endif %} alert-dismissible fade show"
    role="alert">
    {% if messages %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    {% else %}
    {{ form.non_field_errors }}
    {% endif %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endif %}
  {% with user=request.user %}

  <div class="post_detail_wrapper">
    <div class="">
      {% if post.image %}
      <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post_img">
      {% else %}
      <img src="{% static 'img/posts/default_img.png'%}" alt="{{ post.title }}" width="400" style="border-radius: 8px;">
      {% endif %}
    </div>
    <div class="d-flex flex-column w-100">
      <div class="title-cost_block">
        <h5 class="post_detail_title">{{ post.title }} <span>{% if post.is_favorite %}
            <svg fill="#dc3623" height="24px" width="24px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 230 230" xml:space="preserve" stroke="#dc3623">
              <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
              <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
              <g id="SVGRepo_iconCarrier">
                <path
                  d="M213.588,120.982L115,213.445l-98.588-92.463C-6.537,96.466-5.26,57.99,19.248,35.047l2.227-2.083 c24.51-22.942,62.984-21.674,85.934,2.842L115,43.709l7.592-7.903c22.949-24.516,61.424-25.784,85.936-2.842l2.227,2.083 C235.26,57.99,236.537,96.466,213.588,120.982z">
                </path>
              </g>
            </svg>

            {% endif %}</span></h5>
        {% if post.cost %}
        <div class="d-flex">
          <div class="post_detail_cost">Цена: {{ post.cost }}тг</div>
        </div>
        {% endif %}
      </div>
      <div class="post_detail_desc">{{ post.description }}</div>
      <hr>
      <div class="post_detail_autor_contact">
        <div style="font-weight: 600;">{{ post.user_id.first_name }} {{ post.user_id.last_name }}</div>
        <div class="d-flex post_detail_phone-number">
          <a href="tel:{{ post.user_id.phone_number }}" class="post_detail_phone-number_block" id="tel">
            {{ post.user_id.phone_number }}
          </a>
          <button class="post_detail_phone-number_btn" id="phone">Показать номер телефона</button>
        </div>
      </div>
      <div class="d-flex justify-content-between">
        <div class="post_detail_autor">Опубликовано: {{ post.created_at }}</div>
        {% if not is_favorite %}
        <form action="{% url 'posts:favorite_post' post.pk %}" method="post">
          {% csrf_token %}
          <button type="submit" style="background-color: inherit; border: 0;">
            <svg fill="#ffffff" height="28px" width="28px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-56.6 -56.6 584.90 584.90" xml:space="preserve"
              stroke="#ffffff" transform="rotate(0)matrix(-1, 0, 0, 1, 0, 0)" stroke-width="28.773761">
              <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
              <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC"
                stroke-width="5.660412"></g>
              <g id="SVGRepo_iconCarrier">
                <g>
                  <path
                    d="M433.601,67.001c-24.7-24.7-57.4-38.2-92.3-38.2s-67.7,13.6-92.4,38.3l-12.9,12.9l-13.1-13.1 c-24.7-24.7-57.6-38.4-92.5-38.4c-34.8,0-67.6,13.6-92.2,38.2c-24.7,24.7-38.3,57.5-38.2,92.4c0,34.9,13.7,67.6,38.4,92.3 l187.8,187.8c2.6,2.6,6.1,4,9.5,4c3.4,0,6.9-1.3,9.5-3.9l188.2-187.5c24.7-24.7,38.3-57.5,38.3-92.4 C471.801,124.501,458.301,91.701,433.601,67.001z M414.401,232.701l-178.7,178l-178.3-178.3c-19.6-19.6-30.4-45.6-30.4-73.3 s10.7-53.7,30.3-73.2c19.5-19.5,45.5-30.3,73.1-30.3c27.7,0,53.8,10.8,73.4,30.4l22.6,22.6c5.3,5.3,13.8,5.3,19.1,0l22.4-22.4 c19.6-19.6,45.7-30.4,73.3-30.4c27.6,0,53.6,10.8,73.2,30.3c19.6,19.6,30.3,45.6,30.3,73.3 C444.801,187.101,434.001,213.101,414.401,232.701z">
                  </path>
                </g>
              </g>
            </svg>
          </button>
        </form>
        {% else %}
        <form action="{% url 'posts:remove_favorite_post' post.pk %}" method="post">
          {% csrf_token %}
          <button type="submit" style="background-color: inherit; border: 0;">
            <svg fill="#dc3623" height="28px" width="28px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 230 230" xml:space="preserve" stroke="#dc3623">
              <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
              <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
              <g id="SVGRepo_iconCarrier">
                <path
                  d="M213.588,120.982L115,213.445l-98.588-92.463C-6.537,96.466-5.26,57.99,19.248,35.047l2.227-2.083 c24.51-22.942,62.984-21.674,85.934,2.842L115,43.709l7.592-7.903c22.949-24.516,61.424-25.784,85.936-2.842l2.227,2.083 C235.26,57.99,236.537,96.466,213.588,120.982z">
                </path>
              </g>
            </svg>
          </button>
        </form>
        {% endif %}
      </div>
      {% if user.is_authenticated and user == post.user_id %}
      <div class="my-3">
        <!-- <a href="{% url 'posts:delete_post' post.pk %}" class="post_detail_btn-del">Удалить</a> -->
        {% if not post.archived %}
        <form action="{% url 'posts:archive_post' post.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="post_detail_btn-del">Архивировать</button>
        </form>
        {% else %}
        <div class="alert alert-warning" role="alert">
          Объявление в архиве!
        </div>
        <form action="{% url 'posts:return_post' post.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="post_detail_btn-del">Вернуть объявление</button>
        </form>
        {% endif %}
      </div>
      {% endif %}
    </div>

  </div>
</div>

<script>
  const phone = document.getElementById('phone');
  const tel = document.getElementById('tel');
  phone.addEventListener('click', () => {
    tel.classList.toggle('show')
  })
</script>


{% endwith %}
{% endblock %}